services:
  backend:
    build: 
      context: ./backend # Aponta para onde está o Dockerfile
    container_name: finance_backend
    ports:
      # 🚀 SEGURANÇA: Exposto apenas para o localhost (Nginx)
      - "127.0.0.1:8000:8000" 
    env_file:
      - ./backend/.env
    networks:
      - finance_network
    # 🚀 RESILIÊNCIA: Reinicia automaticamente, a menos que você pare manualmente
    restart: unless-stopped 

networks:
  finance_network:
    driver: bridge