services:
  backend:
    build: 
      context: ./backend # Aponta para onde está o Dockerfile
    container_name: finance_backend
    ports:
      - "8000:8000" # Porta PC : Porta Container
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env # Lê as senhas do arquivo .env
    networks:
      - finance_network
    # Reinicia se cair (bom para dev)
    restart: on-failure

networks:
  finance_network:
    driver: bridge